version: "3.7"
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ../crates/infra/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nettuscheduler
  # app:
  #   build: ..
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     NETTU_POSTGRES_CONNECTION_STRING: postgresql://postgres:5432/nettuscheduler
  #   volumes:
  #     - ../:/var/application
  #   command: bash -c "cargo watch -x run"
  #   init: true
  #   entrypoint:
  #     - "integrations/wait-for.sh"
  #     - "postgres:5432"
  #     - "--"

volumes:
  postgresdata:
