[package]
name = "nittei_api"
version = "0.1.0"
authors = ["Meetsmore", "Fredrik Meringdal"]
edition = "2024"

[lints]
workspace = true

[dependencies]
nittei_api_structs = { workspace = true }
nittei_domain = { workspace = true }
nittei_infra = { workspace = true }
nittei_utils = { workspace = true }

axum = "0.8.1"
axum-valid = "0.23.0"
tower-http = { version = "0.6.2", features = [
  "cors",
  "compression-full",
  "decompression-full",
  "trace",
  "sensitive-headers",
  "catch-panic",
] }
tower = "0.5.2"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
validator = { version = "0.18", features = ["derive"] }
awc = "3.5"
async-trait = "0.1.83"
rrule = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
chrono-tz = "0.9.0"
anyhow = "1.0"
jsonwebtoken = "7"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1.25"
tracing-futures = "0.2.5"

[dev-dependencies]
serial_test = "*"
