name: Docker deploy

on: [push]
# on:
#   workflow_run:
#     workflows: ["Test"]
#     branches: [master]
#     types:
#       - completed
jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: fmeringdal
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker compose stack
        run: |
          cd scheduler
          docker-compose -f ./integrations/docker-compose.yml up -d
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./scheduler
          push: true
          tags: fmeringdal/nettu-scheduler:latest
