name: JavaScript client tests

on: [pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nettuscheduler
        ports:
          - 5432:5432
    env:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@localhost/nettuscheduler
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: scheduler/clients/javascript/package-lock.json

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            scheduler/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Start server and run JS client tests
        run: |
          cd scheduler

          # run the migrations first
          cargo install sqlx-cli --no-default-features --features postgres || true
          (cd crates/infra && sqlx migrate run)

          export CREATE_ACCOUNT_SECRET_CODE=opqI5r3e7v1z2h3P
          export RUST_LOG=error,tracing=info

          cargo run --bin nettu_scheduler &

          sleep 10

          cd scheduler/clients/javascript

          npm i -g typescript
          npm i

          npm run test
