name: PR

on: [pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/nettuscheduler
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            scheduler/target/debug
          key: cargo

      - name: Build docker compose stack
        run: |
          cd scheduler
          docker-compose -f ./integrations/docker-compose.yml up -d

      - name: Run tests
        run: |
          cd scheduler
          # https://github.com/xd009642/tarpaulin/issues/756
          cargo test --all
