# https://birtony.medium.com/setting-up-automated-release-workflow-with-github-actions-628dbca2446e
name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    # Unfortunately, regex are not fully supported in YAML files, so we cannot
    # use the officially recommended regex to verify the semantic versioning tag
    # https://github.com/semver/semver/blob/master/semver.md#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  docker-release:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nettuscheduler
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost/nettuscheduler
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo "before"
          echo $RELEASE_VERSION
          echo "after"
          echo ${{ env.RELEASE_VERSION }}
          echo "last"
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       scheduler/target/
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: fmeringdal
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Run migrations
      #   run: |
      #     cd scheduler
      #     cargo install sqlx-cli --no-default-features --features postgres || true
      #     (cd crates/infra && sqlx migrate run)

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./scheduler
      #     push: true
      #     tags: fmeringdal/nettu-scheduler:latest
